# Generated by Django 4.0.4 on 2022-05-27 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('answer', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Submitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.CharField(max_length=150)),
                ('date', models.DateTimeField(verbose_name='time of answer submission')),
                ('correct', models.BooleanField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddleme.puzzle')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_count', models.IntegerField(default=0)),
                ('first_solve', models.DateTimeField(verbose_name='date of first correct answer')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddleme.puzzle')),
            ],
        ),
    ]
