# Generated by Django 4.0.4 on 2022-06-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riddleme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitted',
            name='submitted',
        ),
    ]
