# Generated by Django 4.0.4 on 2022-06-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddleme', '0002_remove_submitted_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitted',
            name='submitted',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
