# Generated by Django 4.0.4 on 2022-06-04 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riddleme', '0003_submitted_submitted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puzzle',
            options={'verbose_name': 'Zagadka', 'verbose_name_plural': 'Zagadki'},
        ),
        migrations.AlterModelOptions(
            name='puzzlestatistics',
            options={'verbose_name': 'Statystyki zagadek', 'verbose_name_plural': 'Statystyki zagadek'},
        ),
        migrations.AlterModelOptions(
            name='submitted',
            options={'verbose_name': 'Zgłoszenie', 'verbose_name_plural': 'Zgłoszenia'},
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='answer',
            field=models.CharField(max_length=150, verbose_name='Odpowiedź'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='content',
            field=models.TextField(verbose_name='Zawartość'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='title',
            field=models.TextField(verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='puzzlestatistics',
            name='first_solve',
            field=models.DateTimeField(verbose_name='Data pierwszego rozwiązania'),
        ),
        migrations.AlterField(
            model_name='puzzlestatistics',
            name='pid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='riddleme.puzzle', verbose_name='ID zagadki'),
        ),
        migrations.AlterField(
            model_name='puzzlestatistics',
            name='solved_count',
            field=models.IntegerField(default=0, verbose_name='Liczba rozwiązań'),
        ),
        migrations.AlterField(
            model_name='submitted',
            name='correct',
            field=models.BooleanField(verbose_name='Czy poprawna odpowiedź'),
        ),
        migrations.AlterField(
            model_name='submitted',
            name='date',
            field=models.DateTimeField(verbose_name='Data zgłoszenia odpowiedzi'),
        ),
        migrations.AlterField(
            model_name='submitted',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riddleme.puzzle', verbose_name='ID zagadki'),
        ),
        migrations.AlterField(
            model_name='submitted',
            name='submitted',
            field=models.CharField(max_length=150, verbose_name='Zgłoszona odpowiedź'),
        ),
        migrations.AlterField(
            model_name='submitted',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID użytkownika'),
        ),
    ]
